spring.application.name=demo

# Configuration de SQLite
spring.datasource.url=jdbc:sqlite:demo.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=com.backendStudent.demo.Config.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
